export default {
    SignUp_Name: '[data-qa="signup-name"]',
    SignUp_Email: '[data-qa="signup-email"]',
    SignUp_Button: '[data-qa="signup-button"]',
    Title_Mr: '#uniform-id_gender1',
    PasswordField: '#password',
    Calender_Date: '#days',
    Calender_Month: '#months',
    Calender_Year: '#years',
    Newsletter_Checkbox: '#newsletter',
    SpecialOffer_Checkbox: '#optin',
    FirstName: '#first_name',
    LastName: '#last_name',
    Company: '#company',
    Address1: '#address1',
    Country_Drd: '#country',
    State: '#state',
    City: '#city',
    Zipcode: '#zipcode',
    Mobile: '#mobile_number',
    CreateAccount_Button: 'button[type="submit"]',
    AccountCreated_Val: '.title.text-center',
    Logout: 'a[href="/logout"]',
    LoginSignup: 'a[href="/login"]',
    Add2Cart_Btn: ':nth-child(3) > .product-image-wrapper > .single-products > .productinfo > .btn',
    Continue_Shopping: '.modal-footer > .btn',
    View_Cart: '.shop-menu > .nav > :nth-child(3) > a',
    Login_Email: '[data-qa="login-email"]',
    Login_Password: '[data-qa="login-password"]',
    Login_Button: '[data-qa="login-button"]',
    Login_Msg: '[action="/login"] > p',
    Delete_Account: 'a[href="/delete_account"]',

    //Swag Lab
    Swag_Uname: '#user-name',
    Swag_Pwd: '#password',
    Swag_Login_Button: '#login-button',
    Swag_HomePage_Val: '.product_label',
    Swag_Sort_Button: '.product_sort_container',
    Swag_Item_Prices: '.inventory_item_price',
    Swag_Cart: 'a[href="./cart.html"]',
    Swag_Checkout: '.btn_action.checkout_button',
    sCart_Fname: '#first-name',
    sCart_Lname: '#last-name',
    sCart_ZipCode: '#postal-code',
    sCart_Continue: '.btn_primary.cart_button',
    sCart_Finish: '.btn_action.cart_button',
    sCart_Success: '#checkout_complete_container > h2',
}